#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  jay-frontend
        bind *:80
        mode http
        default_backend jay-backend
backend jay-backend
        balance roundrobin
        server 422529-web-01 52.91.123.61:80 check
        server 422529-web-02 18.204.14.209:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
